language: 
  node_js
node_js:
  - 6.3.1
  - 5.1
branches:
  only:
    - master
before_script:
  # install dependencies
  - echo "do somthing before_script"
  
install:
  - npm install

after_script:
  - curl localhost:3000/secret

os:
  - linux
